### ISSUE TITLE
Custom rules not being applied

### ISSUE THREAD

**Issue by bockensm** [commandbox-modules/commandbox-codechecker#12]
Here's a repro case: [codechecker-verification.zip](https://github.com/commandbox-modules/commandbox-codechecker/files/8225725/codechecker-verification.zip)

I would expect that when running `codechecker run --verbose` I would have one item found. I did some investigation on my own and found that in codechecker-core, specifically the "runRules" function, `arguments.categories` is empty so it doesn't apply the rule I have defined.

I also tried `codechecker run categories="Custom Rules" --verbose` both with and without the "includeRules" key in the JSON config and neither found the violation I expected to see.

Versions:
commandbox-codechecker 1.3.3
codechecker-core 1.3.1

**Comment by bdw429s** [comment]
Hmm yes, this is a victim of some refactoring that happened in there.  The codecheckerservice CFC has passed through many hands and is a bit of a mess.  There's a lot of dead code in there, and some that the codechecker app probably uses, but I don't even know if anyone uses the app any longer.  

The rules array in the service used to contain all rules and then the category was used at runtime to decide which ones to run.  When the JSON config was added with the ability to filter specific rules, the rules array was changed to contain only the rules that needed run (decided ahead of time in the configure method) and then they are just supposed to all be used.  The varscoper and query param scanner have always been odd because they were never really proper rules so there was custom logic to try and figure out when to run them.   We probably need to start inserting placeholder rules for varscoper and queryparamscanner into the rules array and just remove any of that category filtering logic as that's supposed to happen in the configure method now.

What's funnier is this has probably been broken for a long time, but this module doesn't see a lot of use so no one noticed.

**Comment by bdw429s** [comment]
Man, I really dislike working on this code, lol. It's just a mess and you can tell a lot of people have hacked on it over the years.   I think custom rules are running now.  Please test.

**Comment by bockensm** [comment]
I am happy to report that this appears to be functioning as expected again.
